modLoader="javafml" #mandatory
loaderVersion="39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="dracoshoard" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Draco's Hoard" #mandatory
creduts="George" #optional
authors="Coda" #optional
description='''
Draco's Hoard is a library used by all Team Draco mods, as well as a few others.'''
[[dependencies.dracoshoard]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.dracoshoard]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
