modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="weecore" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Wee Core" #mandatory
logoFile="weecore.png" #optional
creduts="George K" #optional
authors="Coda" #optional
description='''
Wee Core is a library used by all Team Draco mods, as well as a few others.'''
[[dependencies.weecore]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.weecore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
